// <auto-generated />
namespace CSC_CA2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tst : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tst));
        
        string IMigrationMetadata.Id
        {
            get { return "202006301135020_tst"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
