// <auto-generated />
namespace CSC_CA2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatetable4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetable4));
        
        string IMigrationMetadata.Id
        {
            get { return "202006281543218_updatetable4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
